### ISSUE TITLE
Opt-out-Möglichkeit ?

### ISSUE THREAD

**Issue by MurrayBozinsky** [thielul/CallmapGermany#1]
Hallo,
gibt es eine Opt-out-Möglichkeit für die Kartendarstellung ?

**Comment by RipperFox** [comment]
Wenn die Adresse nich bei der Bundesnetzagentur gelistet ist erscheint man logischerweise auch nicht auf der Karte. Falls man der Veröffentlichung seiner Adressdaten nicht widersprochen hat stehen die Daten sowieso schon im Netz.

**Comment by thielul** [comment]
Sollte mit der anonymisierten Version behoben sein.

**Comment by df8oe** [comment]
Ich kann Dich verstehen dass Du keine Diskussionen dieser Art haben möchtest. Daher ist die Umstellung zwar schade - aber wohl notwendig.

Noch weniger verstehen kann ich allerdings OMs, die der Darstellung auf einer Karte widersprechen wollen, Wie schon geschrieben erscheinen sowieso nur die Buttons, wo der Inhaber der Veröffentlichung seiner Adresse bei der BNetzA zugestimmt hat. Und die meisten der "Widersprecher" dürften mit der Nutzung von "Windows", "Facebook", "Whats App" und "Google" täglich weit mehr und weit subtilere Daten völlig freiwillig preisgeben. Und: vergesst nicht, der Veröffentlichung eurer Adresse bei der BNetzA sofort zu widersprechen!

Ja, ich kenne die Antwort: "...aber das ist doch etwas ganz anderes!" - aber ich will so einen Schmarrn nicht hören und ignoriere ihn, da 1 != 0 :)

vy 73
Andreas
