### ISSUE TITLE
Possible migration to OpenStreetMaps?

### ISSUE THREAD

**Issue by df8oe** [thielul/CallmapGermany#2]
Hi Ulrich,

congrats - nice work! I am actually working on migrating all my google maps projects to OSM because it is free (and will be free forever - nobody knows what will happen with google maps and API-Keys) and users are not tracked. Nice start is using "leaflet" library. Maybe this is interesting for you, too. If there are free and open solutions I prefer these...

73's
Andreas

**Comment by thielul** [comment]
Hi Andreas,

das OSM Geocoding kann man direkt im Skript makegeo.py alternativ benuzten (google durch osm ersetzen). Von der Datenbank aus kann man das natürlich visualisieren wo man möchte. Mit makekml.py kann man auch KML-Dateien erstellen (habe ich jetzt nicht weiter verfolgt).

73,
Ulrich

**Comment by df8oe** [comment]
Hi Ulrich,

vielen Dank für die schnelle Antwort. Da hätte ich (mal wieder) zuerst den Code anschauen müssen und dann die Frage stellen :) Und genau das werde ich nachher tun (mir den Code anschauen). Super Idee - super gemacht. Da fallen mir noch weitere Features ein.... Z.B. die Darstellung einer Station (aus er ganzen Welt) aufgrund des bei qrz.com eingegebenen Locators. Das ist zwar je nachdem wie genau dieser angegeben ist mit einer gewissen Unschärfe versehen - aber trotzdem ein nettes Feature. Ich scahue mal in den Code...

73
Andreas

**Comment by thielul** [comment]
Die Möglichkeiten sind unbegrenzt. Good coding, und halt mich auf dem Laufenden.

73
Ulrich

**Comment by df8oe** [comment]
Ich werde mir dein Repo auf den Rechner holen und bei interessanten Dingen einfach einen Pull Request machen.
