### ISSUE TITLE
Erstellung der SQLite DB klappt nicht

### ISSUE THREAD

**Issue by dl4zaa** [thielul/CallmapGermany#3]
Hallo Ulrich,

die Callmap ist eine tolle Idee! Schade, dass Du sie wieder vom Server genommen hast.
Ich habe daher versucht, Deiner Anleitung zur folgen und sie mir selbst zu erstellen. Leider bekomme ich beim Erstellen der Datenbank die Fehlermeldung:  
` ralf$ python makedb.py
Traceback (most recent call last):
  File "makedb.py", line 83, in <module>
    street2 = fields[2].split(",")[1]
IndexError: list index out of range`

Die Erstellung des Textfiles _Calls.txt_ zuvor hat wohl geklappt. Zumindest erhielt ich ein Textfile mit dem Inhalt der pdf-Liste. 
Aber bei der o.a. Fehlermeldung komme ich nicht weiter.

Was könnte denn das Problem sein?

Vy 73, Ralf

**Comment by thielul** [comment]
Hallo Ralf,

danke. Sollte in der aktuellen Version behoben sein! (Ich denke es lag daran, dass du pdftotext und nicht wie ich ps2ascii benutzt hast; aber das geht jetzt auch)

73,
Ulrich
